#pragma kernel CSMain

uint a_len;
uint b_len;
uint c_len;
StructuredBuffer<float> a;
StructuredBuffer<float> c_gradient;
RWStructuredBuffer<float> b_gradient;

[numthreads(64, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    const uint i = c_len / b_len;
    for (uint j = 0; j < i; j++)
    {
        const uint c_index = j * b_len + id.x;
        const uint a_index = c_index % a_len;
        b_gradient[id.x] += c_gradient[j * b_len + id.x] * a[a_index];
    }
}