#pragma kernel CSMain

uint a_len;
uint b_len;
uint c_len;
StructuredBuffer<float> b;
StructuredBuffer<float> c_gradient;
RWStructuredBuffer<float> a_gradient;

[numthreads(64, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    const uint i = c_len / a_len;
    for (uint j = 0; j < i; j++)
    {
        const uint c_index = j * a_len + id.x;
        const uint b_index = c_index % b_len;
        a_gradient[id.x] += c_gradient[j * a_len + id.x] * b[b_index];
    }
}