#pragma kernel CSMain

int src_start;
int dst_start;
int src_interval;
int dst_interval;
int stride;
StructuredBuffer<float> src_buffer;
RWStructuredBuffer<float> dst_buffer;

[numthreads(64, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    const uint i = id.x / stride;
    const uint j = id.x % stride;
    dst_buffer[dst_start + (dst_interval + stride) * i + j] = src_buffer[src_start + (src_interval + stride) * i + j];
}