#pragma kernel Forward
#pragma kernel Backward

float f;
StructuredBuffer<float> mask;
StructuredBuffer<float> a;
StructuredBuffer<float> b_gradient;
RWStructuredBuffer<float> b;
RWStructuredBuffer<float> a_gradient;

[numthreads(512, 1, 1)]
void Forward(uint3 id : SV_DispatchThreadID)
{
    if (mask[id.x] > 0.5) b[id.x] = f;
    else b[id.x] = a[id.x];
}

[numthreads(512, 1, 1)]
void Backward(uint3 id : SV_DispatchThreadID)
{
    if (mask[id.x] < 0.5) a_gradient[id.x] += b_gradient[id.x];
}