#pragma kernel Forward
#pragma kernel Backward

float p;
StructuredBuffer<float> a;
StructuredBuffer<float> b_gradient;
RWStructuredBuffer<float> b;
RWStructuredBuffer<float> a_gradient;

[numthreads(512, 1, 1)]
void Forward(uint3 id : SV_DispatchThreadID)
{
    b[id.x] = pow(a[id.x], p);
}

[numthreads(512, 1, 1)]
void Backward(uint3 id : SV_DispatchThreadID)
{
    a_gradient[id.x] = b[id.x] * b_gradient[id.x] * p / a[id.x];
}