#pragma kernel CSMain

int n;
StructuredBuffer<float> buffer;
RWStructuredBuffer<float> result;

[numthreads(512, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float average = 0.0;
    for (int i = 0; i < n; i++)
    {
        average += buffer[id.x * n + i];
    }
    average /= n;
    float variance = 0.0;
    for (int i = 0; i < n; i++)
    {
        float f = buffer[id.x * n + i] - average;
        f *= f;
        variance += f;
    }
    result[id.x] = variance / n;
}